---
title             : "Replicability of US-China differences in cognition and perception across 12 tasks"
shorttitle        : "Replicating US-China differences"
author:  
  - name          : "Anjie Cao*"
    affiliation   : "1"
    corresponding : yes    
    address       : "450 Jane Stanford Way, Stanford, 94305"
    email         : "anjiecao@stanford.edu" 
  - name          : "Alexandra Carstensen*"
    affiliation   : "2"
    email         : "abcarstensen@gmail.com"
  - name          : "Shan Gao"
    affiliation   : "3"
    email         : "FIXME"
  - name          : "Michael C. Frank"
    affiliation   : "1"
    address       : "450 Jane Stanford Way, Stanford, 94305"
    email         : "mcfrank@stanford.edu" 

affiliation:
  - id            : "1"
    institution   : "Department of Psychology, Stanford University"
  - id            : "2"
    institution   : "Department of Psychology, University of California, San Diego"
  - id            : "3"
    institution   : "University of Chicago"
  
  

authornote: |
  We gratefully acknowledge Alvin Tan, Joseph Outa, and the members of the Language and Cognition Lab at Stanford for comments and assistance. Experiment 1 was previously reported in abbreviated form in the Proceedings of the Cognitive Science Society as Carstensen et al. (2020).
  
abstract: |
    Cultural differences between the US and China have been investigated using a broad array of psychological tasks measuring differences between cognition, language, perception, and reasoning. Using online convenience samples of adults, we conducted two large-scale replications of a selection of 12 tasks previously reported to show cross-cultural differences. Five of these tasks showed robust cross-cultural differences, while six showed no difference and one showed a small difference in the opposite direction. Tasks showing cross-cultural differences tended to have multiple trials measuring high-level reasoning and language; those that did not show cross-cultural difference included measures of attention/perception or implicit social processes or were initially designed to show differences in children. As in prior work, cross-cultural differences in cognition (in those tasks showing differences) were not strongly related to explicit measures of cultural identity and behavior.

  
keywords          : "replication; cross-cultural differences"
wordcount         : "FIXME"
csl               : "apa6-meta.csl"
bibliography      : "library.bib"

floatsintext      : yes
linenumbers       : yes
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

classoption       : "man"
output            : papaja::apa6_pdf
#pdf_document
#papaja::apa6_pdf
latex_engine        : xelatex
header-includes   :
    - \usepackage{tabu}
    - \usepackage{adjustbox}
    - \usepackage{graphicx}

---


```{r load_utility_packages, include = FALSE}
library(papaja)
library(rmarkdown)
library(tidyverse) 
library(here)
library(tidyboot)
library(glue)
library(cowplot)
library(kableExtra)
library(glue)

here::i_am("writing/CCRR_manuscript.Rmd")

r_refs("library.bib")

source(here("processing_pipelines/helper/plotting/plot_es.R"))
source(here("processing_pipelines/helper/plotting/plot_reliability.R"))
source(here("processing_pipelines/helper/plotting/plot_megaplot.R"))
source(here("processing_pipelines/helper/plotting/plot_table.R"))

```


```{r global_options, include = FALSE}

knitr::opts_chunk$set(warning = FALSE, 
                      message = FALSE, 
                      cache = FALSE,
                      echo = FALSE
                      )
knitr::opts_chunk$set(dev = 'pdf')


knitr::opts_knit$set(root.dir = here())

theme_set(theme_classic(base_size = 11))
```



# Introduction

```{r child = "writing/sections/01_intro.Rmd"}
```


<!-- \end{landscape} -->

# Experiment 1


## Methods 


```{r child = "writing/sections/02_exp1_methods.Rmd"}
```




## Results

```{r child = "writing/sections/03_exp1_results.Rmd"}
```  



# Experiment 2

## Discussion

```{r child = "writing/sections/04_exp1_discussion.Rmd"}
```




## Methods

```{r child = "writing/sections/05_exp2_methods.Rmd"}
```

## Results

```{r child = "writing/sections/06_exp2_results.Rmd"}
```




# Exploratory analysis

<!-- ## Mini meta-analysis -->

```{r child = "writing/sections/07_ea_mini_ma.Rmd"}
```

## Reliability assessment

```{r child = "writing/sections/08_ea_reliability_assessment.Rmd"}
```

## Relations between individual tasks

```{r child = "writing/sections/09_ea_relations_between_tasks.Rmd"}
```

## Demographic variation and explicit measures of cultural identity

```{r child = "writing/sections/10_demog_variation.Rmd"}
```

# General Discussion

```{r child = "writing/sections/11_general_discussion.Rmd"}
```



---
nocite: | 
...
  
```{r appendix}
#render_appendix("appendix.Rmd")
```

\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

\newpage

# References

::: {#refs custom-style="Bibliography"}
:::
