---
title: "exp2_01_main_models.rmd"
author: "anjie"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(here)
library(lme4)
library(lmerTest)

library(rstanarm)
library(brms)
library(bridgesampling)


source(here("processing_pipelines/helper/tidy_model_helper.R"))
tidy_d <- read_csv(here("data/03_processed_data/exp2/tidy_main.csv"))
```

```{r}

GLMER_MODEL_DIR <- here("cached_results/exp2/raw_models/glmer_models/")
BAYES_MODEL_DIR <- here("cached_results/exp2/raw_models/bayes_models/")

GLMER_SUMMARY_PATH <- here("cached_results/exp2/glmer_model_summary.RDS")

```

# Run models 

## Ambiguous RMTS

### glmer 

```{r}
rmts_df <- tidy_d %>% 
  filter(task_name == "RMTS") %>% 
  mutate(choice = as.numeric(resp)) %>%
  group_by(subject) %>% 
  mutate(trial_num = row_number()) %>% 
  select(-resp, -task_info, -trial_info, -resp_type)
# model 0: not converging 
#rmts_model <- glmer(choice ~ culture + (trial_num | subject), family = binomial, data = rmts_df)

# model 1: 
rmts_model <- glmer(choice ~ culture + (1 | subject), family = binomial, data = rmts_df)
save_model(rmts_model, GLMER_MODEL_DIR)
```

### bayes 

```{r}
full_b_rmts_model <-  brms::brm(
    choice ~ culture + (trial_num | subject), 
    family = "binomial",
    data = rmts_df,
    prior =  c(
              set_prior("normal(0, 0.5)", class = "b", coef = "cultureUS"),
              set_prior("normal(0,1.5)", class = "Intercept")),
    save_pars = save_pars(all = TRUE), 
    control = list(adapt_delta = 0.999, max_treedepth = 15),
    cores = 4, 
    iter = 9000,
    seed = 11111,
    file = here("cached_results/exp2/raw_models/bayes_models/full_b_rmts_model_ms.Rds"))


null_b_rmts_model <-  brms::brm(
    choice ~ 1 + (trial_num | subject), 
    family = "binomial",
    data = rmts_df,
    prior =  c(set_prior("normal(0,1.5)", class = "Intercept")),
    save_pars = save_pars(all = TRUE), 
    control = list(adapt_delta = 0.999, max_treedepth = 15),
    cores = 4, 
    iter = 9000,
    seed = 11111,
    file = here("cached_results/exp2/raw_models/bayes_models/null_b_rmts_model+ms.Rds"))


```





## Picture Free Description  

### glmer 

```{r}
mention_df <- tidy_d %>% 
  filter(task_name == "FD", resp_type == "first_mention_focal") %>% 
    mutate(first_mention = as.numeric(resp), 
    scene = trial_info) %>% 
  select(-resp, -task_info, -resp_type, -trial_info)
fd_mention_model <- glmer(first_mention ~ culture + (1 | subject)+(culture | scene), family = binomial, data = mention_df)

save_model(fd_mention_model, GLMER_MODEL_DIR)

```

### bayes 

```{r}

full_b_fd_firstmention_model <- brm(
  first_mention ~ culture + (1 | subject)+(culture | scene), 
  data = mention_df, 
  family = "binomial",
  prior =  c(
              set_prior("normal(0, 0.5)", class = "b", coef = "cultureUS"),
              set_prior("normal(0,1.5)", class = "Intercept")),
    save_pars = save_pars(all = TRUE), 
    control = list(adapt_delta = 0.999, max_treedepth = 15),
    cores = 4, 
    iter = 5000,
    seed = 11111,
    file = here("cached_results/exp2/raw_models/bayes_models/full_b_fd_firstmention_model.Rds")

)

null_b_fd_firstmention_model <- brm(
  first_mention ~ 1 + (1 | subject)+(culture | scene), 
  data = mention_df, 
  family = "binomial",
  prior =  c(set_prior("normal(0,1.5)", class = "Intercept")),
  save_pars = save_pars(all = TRUE), 
  control = list(adapt_delta = 0.999, max_treedepth = 15),
  cores = 4, 
  iter = 5000,
  seed = 11111,
  file = here("cached_results/exp2/raw_models/bayes_models/null_b_fd_firstmention_model.Rds"))
 
```


## Change Detection 

### glmer 

```{r}
cd_df <- tidy_d %>% 
  filter(task_name == "CD") %>% 
  mutate(reaction_time = as.numeric(resp), 
         type_of_change = task_info,
         picture = trial_info) %>% 
  select(culture, subject,reaction_time,type_of_change, picture) %>% 
  filter(!is.na(reaction_time))

#cd_model <- lmer(log(reaction_time) ~ culture * type_of_change + (type_of_change | subject) + (culture | picture),  data = cd_df)

#cd_model <- lmer(log(reaction_time) ~ culture * type_of_change + (type_of_change | subject) ,  data = cd_df)

cd_model <- lmer(log(reaction_time) ~ culture * type_of_change + (1 | subject) ,  data = cd_df)
save_model(cd_model, GLMER_MODEL_DIR)

```

### bayes 

```{r}
full_b_cd_model <- brm(
  log(reaction_time) ~ culture * type_of_change + (type_of_change | subject) + (culture | picture), 
  data = cd_df, 
  family = "gaussian",
  prior =  c(
              set_prior("normal(0, 0.92)", class = "b", coef = "cultureUS"),
              set_prior("normal(0, 0.92)", class = "Intercept")),
    save_pars = save_pars(all = TRUE), 
    control = list(adapt_delta = 0.99, max_treedepth = 15),
    cores = 4, 
    iter = 5000,
    seed = 11111,
    file = here("cached_results/exp2/raw_models/bayes_models/full_b_cd_model_log.Rds")
)


null_b_cd_model <- brm(
  log(reaction_time) ~ culture + type_of_change + (type_of_change | subject) + (culture | picture), 
  data = cd_df, 
  family = "gaussian",
  prior =  c(
              set_prior("normal(0, 0.92)", class = "b", coef = "cultureUS"),
              set_prior("normal(0, 0.92)", class = "Intercept")),
    save_pars = save_pars(all = TRUE), 
    control = list(adapt_delta = 0.99, max_treedepth = 15),
    cores = 4, 
    iter = 5000,
    seed = 11111,
    file = here("cached_results/exp2/raw_models/bayes_models/null_b_cd_model_log.Rds")
)

log_null_b_cd_model <- update(null_b_cd_model, prior = c(
              set_prior("normal(0, 0.92)", class = "b", coef = "cultureUS"),
              set_prior("normal(0, 0.92)", class = "Intercept")),
              file = here("cached_results/exp2/raw_models/bayes_models/log_null_b_cd_model.Rds"))
```


## Symbolic Self-Inflation 

### glmer 

```{r}
ssi_df <- tidy_d %>% 
  filter(task_name == "SSI") %>% 
  filter(resp_type == "task_score_ratio") %>% 
  mutate(score = as.numeric(resp)) %>% 
  select(-resp, -task_info, -trial_info, -resp_type)

ssi_model <- glm(score ~ culture, family=gaussian, data = ssi_df)
save_model(ssi_model, GLMER_MODEL_DIR)
```


### bayes 

```{r}
full_b_ssi_model <-  brms::brm(
    score ~ culture,
    family = "gaussian",
    prior =  c(
              set_prior("normal(0, 2.5)", class = "b", coef = "cultureUS"),
              set_prior("normal(0, 2.5)", class = "Intercept")),
    save_pars = save_pars(all = TRUE), 
    data = ssi_df, 
    file = here("cached_results/exp2/raw_models/bayes_models/full_b_ssi_model.Rds")
    )

null_b_ssi_model <- brms::brm(
    score ~ 1,
    family = "gaussian",
    prior =  c(set_prior("normal(0, 2.5)", class = "Intercept")),
    save_pars = save_pars(all = TRUE), 
    data = ssi_df , 
    file = here("cached_results/exp2/raw_models/bayes_models/null_b_ssi_model.Rds")
    )

```


## Causal Attribution 

### glmer 

```{r}
ca_df <- tidy_d %>% 
  filter(task_name == "CA") %>% 
  mutate(attribution_type = task_info, 
         item = trial_info,
         rating = as.numeric(resp)) %>% 
  select(culture, subject,attribution_type,item, rating)

# ca_model <- glmer(rating ~ culture * attribution_type + (attribution_type | subject) + (culture | item),  data = ca_df)

ca_model <- lmer(rating ~ culture * attribution_type + (attribution_type | subject) + (1 | item),  data = ca_df)

save_model(ca_model, GLMER_MODEL_DIR)

```

### bayes 

```{r}
full_b_ca_model <- brms::brm(
  rating ~ culture * attribution_type + (attribution_type | subject) + (culture | item),  
  data = ca_df,
  family = "gaussian",
  prior =  c(
              set_prior("normal(0, 2.5)", class = "b", coef = "cultureUS"),
              set_prior("normal(0, 2.5)", class = "Intercept")),
    save_pars = save_pars(all = TRUE), 
    control = list(adapt_delta = 0.999, max_treedepth = 15),
    cores = 4, 
    iter = 5000,
    seed = 11111,
    file = here("cached_results/exp2/raw_models/bayes_models/full_b_ca_model.Rds")
)

null_b_ca_model <- brms::brm(
  rating ~ culture + attribution_type + (attribution_type | subject) + (culture | item),  
  data = ca_df,
  family = "gaussian",
  prior =  c(
              set_prior("normal(0, 2.5)", class = "b", coef = "cultureUS"),
              set_prior("normal(0, 2.5)", class = "Intercept")),
    save_pars = save_pars(all = TRUE), 
    control = list(adapt_delta = 0.999, max_treedepth = 15),
    cores = 4, 
    iter = 5000,
    seed = 11111,
    file = here("cached_results/exp2/raw_models/bayes_models/null_b_ca_model.Rds")
)
```


## Taxonomic/thematic similarity task

### glmer 

```{r}

triads_d <- tidy_d %>% 
  filter(task_name == "TD") %>% 
  mutate(choice = as.numeric((as.logical(resp))), 
         item = trial_info) %>% 
  select(choice, culture, subject, item)
 

# triads_model <- glmer(choice ~ culture + (1 | subject) + (culture | item), family = binomial, data = triads_d)

td_model <- glmer(choice ~ culture + (1 | subject) + (1 | item), family = binomial, data = triads_d)
#save_model(td_model, GLMER_MODEL_DIR)
```

### bayes 

  
```{r}
full_b_td_model <-  brm(
    choice ~ culture + (1 | subject) + (culture | item), 
    data = triads_d, 
    family = "binomial",
    prior = c(set_prior("normal(0, 0.5)", class = "b", coef = "cultureUS"),
              set_prior("normal(0,1.5)", class = "Intercept")),
    save_pars = save_pars(all = TRUE), 
    control = list(adapt_delta = 0.999, max_treedepth = 15),
    cores = 4, 
    iter = 5000,
    seed = 11111,
    file = here("cached_results/exp2/raw_models/bayes_models/full_b_td_model.Rds"))

null_b_td_model <-  brm(
    choice ~ 1 + (1 | subject) + (culture | item), 
    data = triads_d, 
    family = "binomial",
    prior = c(set_prior("normal(0,1.5)", class = "Intercept")),
    save_pars = save_pars(all = TRUE), 
    control = list(adapt_delta = 0.999, max_treedepth = 15),
    cores = 4, 
    iter = 5000,
    seed = 11111,
    file = here("cached_results/exp2/raw_models/bayes_models/null_b_td_model.Rds"))
```


## Semantic Intuition 

### glmer 

```{r}
SeI_df <- tidy_d %>% 
  filter(task_name == "SeI") %>% 
  filter(task_info == "critical") %>% 
  mutate(
    choice_causal = case_when(
      resp == "causal_historical" ~ TRUE, 
      resp == "descriptivist" ~ FALSE
    )
  ) %>% 
  mutate(item = trial_info) %>% 
  select(choice_causal, culture, subject, item) %>% 
  mutate(choice_causal = as.numeric(choice_causal))

#SeI_model <- glmer(choice_causal ~ culture + (1 | subject) + (culture | item), family = binomial, data = SeI_df)

SeI_model <- glmer(choice_causal ~ culture + (1 | subject) , family = binomial, data = SeI_df, 
                   control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))

SeI_mode_with_item <- glmer(choice_causal ~ culture + item + (1 | subject) , family = binomial, data = SeI_df, 
                   control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))


#save_model(SeI_model, GLMER_MODEL_DIR)

```

### bayes

    
```{r}
full_b_SeI_model <-  brms::brm(
    choice_causal ~ culture + (1 | subject) + (culture | item), 
    data = SeI_df, 
    family = "binomial",
    prior = c(set_prior("normal(0, 0.5)", class = "b", coef = "cultureUS"),
              set_prior("normal(0,1.5)", class = "Intercept")),
    save_pars = save_pars(all = TRUE), 
    control = list(adapt_delta = 0.999, max_treedepth = 15),
    cores = 4, 
    iter = 5000,
    seed = 11111,
    file = here("cached_results/exp2/raw_models/bayes_models/full_b_SeI_model.Rds"))

null_b_SeI_model <-  brms::brm(
    choice_causal ~ 1 + (1 | subject) + (culture | item), 
    data = SeI_df, 
    family = "binomial",
    prior = c(set_prior("normal(0,1.5)", class = "Intercept")),
    save_pars = save_pars(all = TRUE), 
    control = list(adapt_delta = 0.999, max_treedepth = 15),
    cores = 4, 
    iter = 5000,
    seed = 11111,
    file = here("cached_results/exp2/raw_models/bayes_models/null_b_SeI_model.Rds"))
```


## Raven's Standard Progressive Matrices 

### glmer 

```{r}
rv_df <- tidy_d %>% 
  filter(task_name == "RV") %>% 
  mutate(acc = as.numeric(resp)) %>% 
  group_by(subject) %>% 
  mutate(trial = as.factor(row_number())) %>% 
  select(-resp, -task_info, -trial_info, -resp_type)

rv_model <- glmer(acc ~ culture + (1 | subject) + (culture | trial), family = binomial, data = rv_df)
#save_model(rv_model, GLMER_MODEL_DIR)
```

### bayes 


 

```{r}
full_rv_model <-  brms::brm(
    acc ~ culture + (1 | subject) + (culture | trial), 
    data = rv_df, 
    family = "binomial",
    prior = c(set_prior("normal(0, 0.5)", class = "b", coef = "cultureUS"),
              set_prior("normal(0,1.5)", class = "Intercept")),
    save_pars = save_pars(all = TRUE), 
    control = list(adapt_delta = 0.999, max_treedepth = 15),
    cores = 4, 
    iter = 5000,
    seed = 11111,
    file = here("cached_results/exp2/raw_models/bayes_models/full_b_rv_model.Rds"))

null_rv_model <-  brms::brm(
    acc ~ 1 + (1 | subject) + (culture | trial), 
    data = rv_df, 
    family = "binomial",
    prior = c(set_prior("normal(0,1.5)", class = "Intercept")),
    save_pars = save_pars(all = TRUE), 
    control = list(adapt_delta = 0.999, max_treedepth = 15),
    cores = 4, 
    iter = 5000,
    seed = 11111,
    file = here("cached_results/exp2/raw_models/bayes_models/null_b_rv_model.Rds"))

```





# Tidy models 

### tidy glmer model 

```{r}
all_models_str <- list.files(GLMER_MODEL_DIR)
all_model_results <- lapply(all_models_str, tidy_model_main) %>% bind_rows()
saveRDS(all_model_results,GLMER_SUMMARY_PATH)
```

### tidy bayes model

```{r}
all_bayes_models_str <- list.files(BAYES_MODEL_DIR, pattern = "*.(Rds|RDS)")


key_words <- unique(sapply(all_bayes_models_str, 
                           function(s){str_match(s,
                                        "(full|null)_b_\\s*(.*?)\\s*.(RDS|Rds)")[,3]}))
                             
# saving each BF calculation because this function crashes R very frequently 


lapply(key_words, function(kw){
  print(kw)
  for (m_name in all_bayes_models_str){
    if (grepl(kw, m_name) & grepl("full", m_name)){
      full_model_name = m_name
      print(full_model_name)
    }
  }
   for (m_name in all_bayes_models_str){
    if (grepl(kw, m_name) & grepl("null", m_name)){
      null_model_name = m_name
      print(null_model_name)
    }
  }
  
  bf <- bayes_factor(bridge_sampler(readRDS(paste0(BAYES_MODEL_DIR, full_model_name))), 
               bridge_sampler(readRDS(paste0(BAYES_MODEL_DIR, null_model_name))))
  print(bf)
  
  saveRDS(bf, file = paste0(here("cached_results/exp2/raw_models/bayes_models/bfs/"), kw, ".rds"))
  
})

## read in all the bayes factor and make a nice summary df 

all_bayes_factor_str <- list.files(paste0(BAYES_MODEL_DIR, "bfs/"), pattern = "*.rds")
bfs_df <- tibble(
  bfs_type = rep(NA_character_, length(all_bayes_factor_str)),
  bf = rep(NA_real_, length(all_bayes_factor_str))
)

for (i in seq(1, length(all_bayes_factor_str), 1)){
  bfs_df$bfs_type[i] <- str_match(all_bayes_factor_str[i], "(.*?)\\s*_model.rds")[,2]
  bfs_df$bf[i] <- readRDS(paste0(BAYES_MODEL_DIR, "bfs/", all_bayes_factor_str[i]))$bf
}

bfs_df <- bfs_df %>% 
  mutate(bf_print = case_when(
    bf < 0.01 ~ "< 0.01",
    bf > 100 ~ "> 100", 
    TRUE ~ paste0("= ", as.character(round(bf,2)))
    ))
    
saveRDS(bfs_df, here("cached_results/exp2/bfs_summary.RDS"))
```




